build:
  environment:
    selenium: false
    memcached: false
    elasticsearch: false
    rabbitmq: false
    postgresql: false
    redis: false
    php:
      version: 7.1.0
      ini:
        'date.timezone': 'Europe/London'

  cache:
      directories:
          - ~/samknows

  dependencies:

  tests:
    override:
      -
        command: 'cd /home/scrutinizer/build; ./run_tests.sh'
        coverage:
          file: 'tests/_output/coverage.xml'
          format: 'clover'

filter:
  excluded_paths:
    - 'vendor/*'
    - 'app/sql/*'
    - 'app/docker/*'
tools:
#  external_code_coverage: true
  php_analyzer: true
  php_mess_detector: true
  php_code_sniffer:
    config:
      standard: PSR2
    filter:
      paths: ['app', 'public']
  php_loc:
    enabled: true
    excluded_dirs: ['vendor', 'tests', 'sql', 'docker']
  php_cpd:
    enabled: true
    excluded_dirs: ['vendor', 'tests', 'sql', 'docker']
checks:
  php:
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    optional_parameters_at_the_end: true
    no_short_variable_names:
      minimum: '3'
    no_short_method_names:
      minimum: '3'
    no_long_variable_names:
      maximum: '20'
    no_goto: true
    newline_at_end_of_file: true
    more_specific_types_in_doc_comments: true
    encourage_single_quotes: true
    encourage_postdec_operator: true
    classes_in_camel_caps: true
    avoid_multiple_statements_on_same_line: true
    align_assignments: true
    code_rating: true